---

- name: Ensure pip3 is installed
  yum:
    name: python3-pip
    state: latest
  when: ansible_distribution == "CentOS"

# - name: Install Aptitude
#   apt:
#     name: aptitude
#     state: latest
#   when: ansible_distribution == "Ubuntu" or ansible_distribution == "Debian"
 
- name: Update apt
  shell: apt update
  when: ansible_distribution == "Ubuntu" or ansible_distribution == "Debian"
  
- name: Ensure pip3 is installed
  apt:
    name: python3-pip
    state: latest
  when: ansible_distribution == "Ubuntu" or ansible_distribution == "Debian"

- name: Update pip
  shell: pip3 install --upgrade pip
