---
- name: Start Neo4j container
  docker_container:
    name: "{{ container_name }}"
    image: neo4j:3.5.0
    network_mode: "{{ network_name }}"
    published_ports:
      - "0.0.0.0:{{ network_http_port }}:{{ container_http_port }}"
      - "0.0.0.0:{{ network_bolt_port }}:{{ container_bolt_port }}"
    env:
      NEO4J_AUTH: "{{ auth }}"

- name: Specify database access uri
  set_fact:
    db_uri: "bolt://{{ container_name }}:{{ container_bolt_port }}"
    db_ui_port: "{{ network_http_port }}"
    cacheable: yes
...
