

---
- name: Ensure docker for user gitlab-runner
  become: true
  user:
    name: "{{ username }}"
    groups: docker
    append: true

- service:
    name: docker
    state: restarted
    enabled: yes
