version: '3'
services:
  msgprocessor-local:
    image: msgprocessor:latest
    ports:
      - "80:80"
      - "10007:10007"
    environment:
      KAFKABROKERS: test-broker #This should probably be set to DEVELOPMENT
      EVALUATOR: test-evaluator
      EXPERIMENT: test-experiment
      PERFORMER_NAME: test-performer
      SERVICE_NAME: test-Service
      START_TIME_ID: abcd123
      PORT: 80
      ENTRYPOINTPATHSPEC: ${AWS_REGION}
      READINESSCHECKPATHSPEC: this-isnothing
      LIVENESSCHECKPATHSPEC: this-isnothing 
      ESDOMAIN_ENDPOINT: https://kairos.
      ENVIRONMENT_TIER: DEVELOPMENT
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}