# Welcome to Serverless!
#
# This file is the main config file for your service.
#
# For full config options, check the docs:
#    docs.serverless.com

service: kairosserverless
frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.8
  timeout: 900
  iam:
    role: 'arn:aws:iam::130602597458:role/serverless_role'
functions:
  validate:
    handler: handler.handle
    events:
      - s3:
          bucket: kairos-experiment-output
          event: s3:ObjectCreated:*
          rules:
            - suffix: .json
          existing: true
      - s3:
          bucket: kairos-experiment-output
          event: s3:ObjectCreated:*
          rules:
            - suffix: .jsonld
          existing: true
      - s3:
          bucket: kairos-experiment-output
          event: s3:ObjectCreated:*
          rules:
            - suffix: .json-ld
          existing: true