#!/usr/bin/env ansible-playbook -i inventory

---
- name: Wait for systems to come up
  hosts: localhost
  connection: local
  gather_facts: true
  roles:
    - {role: wait-for-ec2,
        tags_to_check: ["tag_Name_Validation_Internal"]}

- name: Add Clotho
  gather_facts: true
  hosts: 
    - "tag_Name_Validation_Internal"
  remote_user: ubuntu
  become: true
  vars:
    db_type: "Validation"
    clotho_tag: "latest"
  roles:
    - role: aws-ecr-checkout
      repo_name: clotho 
      repo_tag: "{{ clotho_tag|lower }}"
      aws_profile: ''
    # Start Clotho app
    - role: bounce-container
      container_name: validation
      image_name: clotho
      image_tag: "{{ clotho_tag|lower }}"
      restart: "always"
      ports:
        - "80:8008"
      env: {
        DB_TYPE: "{{ db_type }}"
      }
