#!/usr/bin/env ansible-playbook -i inventory

---
- name: Create network
  gather_facts: true
  hosts: localhost
  remote_user: local
  become: true
  roles:
    # Retrieve images from ECR via AWS-CLI
    - { role: neptune-proxy, network_name: proxy_net}

...