
---
- name: Wait for systems to come up
  hosts: localhost
  connection: local
  gather_facts: true
  roles:
    - {role: wait-for-ec2,
        tags_to_check: ["tag_Name_zipServer"]}

- name: Configure the instances with common requirements
  hosts: "tag_Name_zipServer"
  gather_facts: true
  remote_user: ubuntu
  become: true
  roles:
    - awscli
    - pip-botos
    - flask-s3-zip-service
    
...
