
---
- name: set facts
  hosts: localhost
  gather_facts: true
  remote_user: local
  become: true
  tasks:
    - set_fact:
        zeus_tag: "{{ zeus_tag | default('latest') }}"
    - set_fact:
        ui_tag: "{{ ui_tag | default('latest') }}"
    - set_fact:
        zeus_image_name: "zeus"
    - set_fact:
        ui_image_name: "ui"
    - set_fact:
        container_network_name: "nginx-network"
    - set_fact:
        zeus_container_name: "{{ zeus_image_name }}-{{ zeus_tag }}"

- name: Pull docker containers
  gather_facts: true
  hosts: localhost
  remote_user: local
  become: true
  roles:
    # Retrieve images from ECR via AWS-CLI
    - { role: aws-ecr-checkout, aws_profile: null, repo_name: zeus, repo_tag: "{{ zeus_tag }}", local_name: "{{ zeus_image_name }}", local_tag: "{{ zeus_tag }}"}
    - { role: aws-ecr-checkout, aws_profile: null, repo_name: ui, repo_tag: "{{ ui_tag }}", local_name: "{{ ui_image_name }}", local_tag: "{{ ui_tag }}"}

- name: Start Containers
  gather_facts: true
  hosts: localhost
  remote_user: local
  become: true
  vars:
    network_name: "{{ container_network_name }}"
    rds_address_env: "{{ lookup('env','rds_address') }}"
    rds_port_env: "{{ lookup('env','rds_port') }}"
    rds_db_name_env: "{{ lookup('env','rds_database_name') }}"
    rds_connector: "jdbc:mysql://{{ rds_address_env }}:{{ rds_port_env }}/{{ rds_db_name_env }}"
    aws_region: "us-east-1"
  roles:
    - role: flask-githook-service
    # Start application
    - role: bounce-container
      restart: "always"
      container_name: "{{ zeus_container_name }}"
      image_name: "{{ zeus_image_name }}"
      ports:
        - "all"
      pause_time: 2
      volumes:
        - /home/ubuntu/moirai-infrastructure/:/usr/src/moirai-infrastructure/
        - /home/ubuntu/moirai-infrastructure/ansible:/usr/src/ansible
        - /home/ubuntu/moirai-infrastructure/key-pairs:/usr/src/key-pairs
        - /home/ubuntu/.aws:/root/.aws
      env: {
        SPRING_DATASOURCE_URL: "{{ rds_connector }}",
        SPRING_DATASOURCE_USERNAME: "{{ lookup('env','rds_username') }}",
        SPRING_DATASOURCE_PASSWORD: "{{ lookup('env','rds_secret') }}",
        AWS_REGION: "{{ aws_region }}",
        ANSIBLE_HOST_KEY_CHECKING: "false",
        AWS_ACCESS_KEY_ID: "{{ lookup('env','aws_access_key') }}",
        AWS_SECRET_ACCESS_KEY: "{{ lookup('env','aws_secret_key') }}",
        ENVIRONMENT_TIER: "{{ lookup('env','environment_tier_zeus') }}",
        MAIL_USERNAME: "{{ lookup('env','mail_username') }}",
        MAIL_PASSWORD: "{{ lookup('env','mail_password') }}",
        SG_AWS_ID_ENV: "{{ lookup('env','sg_aws_id') }}",
        SUBNET_ID_ENV: "{{ lookup('env','subnet_id') }}"
      }
    - role: bounce-container
      restart: "always"
      container_name: "{{ ui_image_name }}-{{ ui_tag }}"
      image_name: "{{ ui_image_name }}"
      ports:
        - "all"
      env: {
        ZEUS_LOCATION: "http://{{ zeus_container_name }}:8000/"
      }
    - {role: kairos-proxy, conf_version: test}
...
