apiVersion: v1
kind: Service
metadata:
  name: nifi-registry-0
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  selector:
    statefulset.kubernetes.io/pod-name: nifi-registry-0
  ports:
  - protocol: TCP
    port: 18080
    targetPort: 18080
