version: '3'
services:
  neo4j:
    image: neo4j:3.5.0
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      NEO4J_AUTH: none
  clotho:
    image: openjdk:11
    volumes:
      - ../build/libs:/jars
    depends_on:
      - neo4j
    links:
      - "neo4j"
    ports:
      - "8008:8008"
      - "8686:8686"
    environment:
      DB_TYPE: "Neo4j"
      DB_URI: "bolt://neo4j:7687"
    working_dir: "/jars/"
    command: "/bin/bash -c 'java -Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.port=8686 -Dcom.sun.management.jmxremote.rmi.port=8686  -Djava.rmi.server.hostname=localhost  -Dcom.sun.management.jmxremote.authenticate=false  -Dcom.sun.management.jmxremote.ssl=false -jar $$(ls moirai-clotho*.jar)'"
